name: Jest Coverage Report for All Commits

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Esto asegura que obtienes todo el historial de commits

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get all commits in push
        run: |
          git log --pretty=format:"%H" origin/${{ github.ref_name }} > commits.txt
        shell: bash

      - name: Loop through commits and run Jest with coverage
        run: |
          while IFS= read -r commit; do
            echo "Checking out commit: $commit"
            git checkout $commit

            npm install

            # Ejecuta Jest con cobertura
            npm test -- --coverage

            echo "Publishing coverage report for commit: $commit"

            # Establecemos GITHUB_SHA en cada commit
            GITHUB_SHA=$commit

            # Usamos jest-coverage-report-action en cada commit
            - name: Publish Jest Coverage Report
              uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                # Puedes configurar las opciones de salida aquí
          done < commits.txt
