jobs:
  test:
    runs-on: ubuntu-latest
    steps:
 name: Jest Coverage Report for All Commits

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Asegura que obtienes todo el historial de commits

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get commit history in push
        run: |
          git log --pretty=format:"%H" origin/${{ github.ref_name }} > commits.txt

      - name: Run Jest for each commit
        run: |
          commits=$(cat commits.txt)
          for commit in $commits; do
            echo "Running tests for commit: $commit"

            # Recorremos los commits uno por uno y ejecutamos Jest
            git checkout $commit
            npm install
            npm test -- --coverage

            # Publicamos el reporte de cobertura
            echo "Publishing coverage report for commit: $commit"
            GITHUB_SHA=$commit
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"Jest Coverage for commit: $commit\"}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/$commit/comments"
          done
